### ISSUE TITLE
老哥可否发一个数据库

### ISSUE THREAD

**Issue by irunmyway** [alexwangfufa/MedicalSystem#4]
没有数据库，老哥可否发一个数据库

**Comment by ziludev** [comment]
> 没有数据库，老哥可否发一个数据库

可以的，感谢查看！如有错误，请提出。

**Comment by irunmyway** [comment]
> > 没有数据库，老哥可否发一个数据库
> 
> 可以的，感谢查看！如有错误，请提出。

我该怎么获取呢？你要上传在仓库吗？

**Comment by ziludev** [comment]
> > > 没有数据库，老哥可否发一个数据库
> > 
> > 
> > 可以的，感谢查看！如有错误，请提出。
> 
> 我该怎么获取呢？你要上传在仓库吗？

刚刚已经上传到仓库了

**Comment by ziludev** [comment]
database file is upload
